### ISSUE TITLE
Vagrantfile is not compatible with current versions of vagrant? 

### ISSUE THREAD

**Issue by cinterloper** [pixelcog/opsworks-local#1]
grant@wrk ~/projects/opsworks-local (git)-[version2] % vagrant up
Setting `id` on a provisioner is deprecated. Please use the
new syntax of `config.vm.provision "name", type: "type"
where "name" is the replacement for`id`. This will be
fully removed in Vagrant 1.8.
Setting`id`on a provisioner is deprecated. Please use the
new syntax of`config.vm.provision "name", type: "type"
where "name" is the replacement for `id`. This will be
fully removed in Vagrant 1.8.
Setting `id` on a provisioner is deprecated. Please use the
new syntax of `config.vm.provision "name", type: "type"
where "name" is the replacement for`id`. This will be
fully removed in Vagrant 1.8.
Bringing machine 'app' up with 'virtualbox' provider...
Bringing machine 'db' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The following settings shouldn't exist: id

chef solo provisioner:
- The following settings shouldn't exist: id
- The following settings shouldn't exist: id

1 grant@wrk ~/projects/opsworks-local (git)-[version2] % vagrant --version  
Vagrant 1.7.1
1 grant@wrk ~/projects/opsworks-local (git)-[version2] % vagrant plugin list                                               vagrant-omnibus (1.4.1)
vagrant-share (1.1.4, system)
grant@wrk ~/projects/opsworks-local (git)-[version2] %

**Comment by mikegreiling** [comment]
Hey @cinterloper, thanks for the issue report and pull request.  I've merged your PR and I have also significantly overhauled the examples found in this repository.  If you were experiencing any issues getting it to work before I'm sure it should be fixed now.
